// my-react-app/src/components/VideoPlayer.jsx
import React from 'react';

const VideoPlayer = ({video, goBack}) => {
  return(
    <div className="video-player-container">
      <div className="video-wrapper">
        <iframe src={'https://www.youtube.com/embed/' + video.videoId} allowFullScreen></iframe>
      </div>
      <div>
        <h3>{video.title}</h3>
        <div className="video-desc">{video.description}</div>
        <button className="search-button btn" onClick={goBack}>Back</button>
      </div>
    </div>
  )
}

export default VideoPlayer;

// my-angular-app/src/app/video-player/video-player.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-video-player',
  templateUrl: './video-player.component.html',
  styleUrls: ['./video-player.component.css']
})
export class VideoPlayerComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="video-player-container">
  <div class="video-wrapper">
    <iframe [src]="sanitizeUrl(currentVideo.videoId)"></iframe>
  </div>
  <div>
    <h3>{{ currentVideo.title }}</h3>
    <div class="video-desc">{{ currentVideo.description }}</div>
    <button class="search-button btn" (click)="goBack()">Back</button>
  </div>
</div>
